// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: capgrant.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCapGranForApp = `-- name: DeleteCapGranForApp :exec

DELETE FROM capgrant where app = $1 and realm = $2
`

type DeleteCapGranForAppParams struct {
	App   pgtype.Text `json:"app"`
	Realm int32       `json:"realm"`
}

func (q *Queries) DeleteCapGranForApp(ctx context.Context, arg DeleteCapGranForAppParams) error {
	_, err := q.db.Exec(ctx, deleteCapGranForApp, arg.App, arg.Realm)
	return err
}
