// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: config.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const configSet = `-- name: ConfigSet :exec
INSERT INTO
    config(
        realm, slice, name, descr, val, setby
    )
VALUES (
        $1, $2, $3, $4, $5, $6
    )
`

type ConfigSetParams struct {
	Realm string      `json:"realm"`
	Slice int32       `json:"slice"`
	Name  string      `json:"name"`
	Descr string      `json:"descr"`
	Val   pgtype.Text `json:"val"`
	Setby string      `json:"setby"`
}

func (q *Queries) ConfigSet(ctx context.Context, arg ConfigSetParams) error {
	_, err := q.db.Exec(ctx, configSet,
		arg.Realm,
		arg.Slice,
		arg.Name,
		arg.Descr,
		arg.Val,
		arg.Setby,
	)
	return err
}
