// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: deactivated.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateRecord = `-- name: ActivateRecord :exec
DELETE FROM deactivated WHERE realm = $1 and "user"= $2
`

type ActivateRecordParams struct {
	Realm  string      `json:"realm"`
	Userid pgtype.Text `json:"userid"`
}

func (q *Queries) ActivateRecord(ctx context.Context, arg ActivateRecordParams) error {
	_, err := q.db.Exec(ctx, activateRecord, arg.Realm, arg.Userid)
	return err
}

const deactivateRecord = `-- name: DeactivateRecord :exec
INSERT INTO deactivated (realm , "user", deactby, deactat)
VALUES ($1,$2,$3,$4)
`

type DeactivateRecordParams struct {
	Realm   string           `json:"realm"`
	Userid  pgtype.Text      `json:"userid"`
	Deactby string           `json:"deactby"`
	Deactat pgtype.Timestamp `json:"deactat"`
}

func (q *Queries) DeactivateRecord(ctx context.Context, arg DeactivateRecordParams) error {
	_, err := q.db.Exec(ctx, deactivateRecord,
		arg.Realm,
		arg.Userid,
		arg.Deactby,
		arg.Deactat,
	)
	return err
}
