// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type App struct {
	ID          int32            `json:"id"`
	Realm       string           `json:"realm"`
	Shortname   string           `json:"shortname"`
	Shortnamelc string           `json:"shortnamelc"`
	Longname    string           `json:"longname"`
	Setby       string           `json:"setby"`
	Setat       pgtype.Timestamp `json:"setat"`
}

type Capgrant struct {
	ID        int32            `json:"id"`
	Realm     int32            `json:"realm"`
	User      string           `json:"user"`
	App       pgtype.Text      `json:"app"`
	Cap       string           `json:"cap"`
	From      pgtype.Timestamp `json:"from"`
	To        pgtype.Timestamp `json:"to"`
	Setat     pgtype.Timestamp `json:"setat"`
	Setby     string           `json:"setby"`
	Isdeleted pgtype.Bool      `json:"isdeleted"`
}

type Config struct {
	Realm int32            `json:"realm"`
	Slice int32            `json:"slice"`
	Name  string           `json:"name"`
	Descr string           `json:"descr"`
	Val   pgtype.Text      `json:"val"`
	Ver   pgtype.Int4      `json:"ver"`
	Setby string           `json:"setby"`
	Setat pgtype.Timestamp `json:"setat"`
}

type Deactivated struct {
	ID      int32            `json:"id"`
	Realm   string           `json:"realm"`
	User    pgtype.Text      `json:"user"`
	Deactby string           `json:"deactby"`
	Deactat pgtype.Timestamp `json:"deactat"`
}

type Realm struct {
	ID          int32            `json:"id"`
	Shortname   string           `json:"shortname"`
	Shortnamelc string           `json:"shortnamelc"`
	Longname    string           `json:"longname"`
	Setby       string           `json:"setby"`
	Setat       pgtype.Timestamp `json:"setat"`
	Payload     []byte           `json:"payload"`
}

type Realmslice struct {
	ID           int32            `json:"id"`
	Realm        string           `json:"realm"`
	Descr        string           `json:"descr"`
	Active       bool             `json:"active"`
	Activateat   pgtype.Timestamp `json:"activateat"`
	Deactivateat pgtype.Timestamp `json:"deactivateat"`
}

type Ruleset struct {
	ID         int32            `json:"id"`
	Realm      int32            `json:"realm"`
	Slice      int32            `json:"slice"`
	App        pgtype.Text      `json:"app"`
	Brwf       string           `json:"brwf"`
	Class      string           `json:"class"`
	Setname    string           `json:"setname"`
	Schemaid   int32            `json:"schemaid"`
	IsActive   pgtype.Bool      `json:"is_active"`
	IsInternal bool             `json:"is_internal"`
	Ruleset    []byte           `json:"ruleset"`
	Createdat  pgtype.Timestamp `json:"createdat"`
	Createdby  string           `json:"createdby"`
	Editedat   pgtype.Timestamp `json:"editedat"`
	Editedby   string           `json:"editedby"`
}

type Schema struct {
	ID            int32            `json:"id"`
	Realm         int32            `json:"realm"`
	Slice         int32            `json:"slice"`
	App           string           `json:"app"`
	Brwf          string           `json:"brwf"`
	Class         string           `json:"class"`
	Patternschema []byte           `json:"patternschema"`
	Actionschema  []byte           `json:"actionschema"`
	Createdat     pgtype.Timestamp `json:"createdat"`
	Createdby     string           `json:"createdby"`
	Editedat      pgtype.Timestamp `json:"editedat"`
	Editedby      string           `json:"editedby"`
}

type Stepworkflow struct {
	Slice    int32       `json:"slice"`
	App      pgtype.Text `json:"app"`
	Step     string      `json:"step"`
	Workflow string      `json:"workflow"`
}

type Wfinstance struct {
	ID       int32            `json:"id"`
	Entityid int32            `json:"entityid"`
	Slice    int32            `json:"slice"`
	App      pgtype.Text      `json:"app"`
	Class    string           `json:"class"`
	Workflow string           `json:"workflow"`
	Step     string           `json:"step"`
	Loggedat pgtype.Timestamp `json:"loggedat"`
	Doneat   pgtype.Timestamp `json:"doneat"`
	Nextstep string           `json:"nextstep"`
	Parent   pgtype.Int4      `json:"parent"`
}
