// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: wfinstance.sql

package sqlc

import (
	"context"
)

const addWFNewInstace = `-- name: AddWFNewInstace :one
INSERT INTO 
wfinstance
(entityid,slice, app, class, workflow, step,loggedat, nextstep)
VALUES ($1,$2,$3,$4,$5,$6,(NOW() :: timestamp),$7) 
RETURNING id
`

type AddWFNewInstaceParams struct {
	Entityid string `json:"entityid"`
	Slice    int32  `json:"slice"`
	App      string `json:"app"`
	Class    string `json:"class"`
	Workflow string `json:"workflow"`
	Step     string `json:"step"`
	Nextstep string `json:"nextstep"`
}

func (q *Queries) AddWFNewInstace(ctx context.Context, arg AddWFNewInstaceParams) (string, error) {
	row := q.db.QueryRow(ctx, addWFNewInstace,
		arg.Entityid,
		arg.Slice,
		arg.App,
		arg.Class,
		arg.Workflow,
		arg.Step,
		arg.Nextstep,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getWFINstance = `-- name: GetWFINstance :many

SELECT id, entityid, slice, app, class, workflow, step, loggedat, doneat, nextstep, parent 
FROM wfinstance
WHERE slice = $1 
AND app = $2
AND workflow = $3
AND entityid = $4
`

type GetWFINstanceParams struct {
	Slice    int32  `json:"slice"`
	App      string `json:"app"`
	Workflow string `json:"workflow"`
	Entityid string `json:"entityid"`
}

func (q *Queries) GetWFINstance(ctx context.Context, arg GetWFINstanceParams) ([]Wfinstance, error) {
	rows, err := q.db.Query(ctx, getWFINstance,
		arg.Slice,
		arg.App,
		arg.Workflow,
		arg.Entityid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Wfinstance
	for rows.Next() {
		var i Wfinstance
		if err := rows.Scan(
			&i.ID,
			&i.Entityid,
			&i.Slice,
			&i.App,
			&i.Class,
			&i.Workflow,
			&i.Step,
			&i.Loggedat,
			&i.Doneat,
			&i.Nextstep,
			&i.Parent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
